// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deleteAddressandZipcodefromEmployeeregisterview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteAddressandZipcodefromEmployeeregisterview));
        
        string IMigrationMetadata.Id
        {
            get { return "201905052023457_delete Address and Zipcode from Employee register view"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
